version: '3'
services:
  nginx:
    image: nginx:1.15.11-alpine
    container_name: nginx-svr
    environment:
      - APP_ENV=prod
    links:
      - php
    ports:
      - "9000:80"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
    # - ./temp/logs:/var/log
    command: [nginx, '-g', 'daemon off;']
  php:
    image: registry.cn-shenzhen.aliyuncs.com/luyuanxun/php7.3.4-fpm-stretch:v1
    container_name: php-svr
    environment:
      - APP_ENV=prod
    ports:
      - "9501:9501"
    volumes:
      - ./:/var/www
